const ProductArray=[
    {
        'id':'1',
        'name':'T-shirt',
        'price':'5000',
        'image':'https://designimages.blob.core.windows.net/theme/Powerhouse/tee.jpg'
    },
    {
        'id':'2',
        'name':'Accesories',
        'price':'5000',
        'image':'https://designimages.blob.core.windows.net/theme/Powerhouse/activewear.jpg'
    },
    {
        'id':'3',
        'name':'Caps',
        'price':'5000',
        'image':'https://designimages.blob.core.windows.net/theme/Powerhouse/hat.jpg'
    },
    {
        'id':'4',
        'name':'Bag',
        'price':'5000',
        'image':'https://designimages.blob.core.windows.net/theme/Powerhouse/bag.jpg'
    },
    {
        'id':'5',
        'name':'T-shirt',
        'price':'5000',
        'image':'https://designimages.blob.core.windows.net/theme/Powerhouse/tee.jpg'
    },
    {
        'id':'6',
        'name':'Accesories',
        'price':'5000',
        'image':'https://designimages.blob.core.windows.net/theme/Powerhouse/activewear.jpg'
    },
    {
        'id':'7',
        'name':'Caps',
        'price':'5000',
        'image':'https://designimages.blob.core.windows.net/theme/Powerhouse/hat.jpg'
    },
    {
        'id':'8',
        'name':'Bag',
        'price':'5000',
        'image':'https://designimages.blob.core.windows.net/theme/Powerhouse/bag.jpg'
    }
]

export default ProductArray